# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "beta" ]
  pull_request:
    branches: [ "beta" ]

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest] 

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install and Pack # 安装依赖并且进行构建
      run: |
        npm install
        npm run build
        pwd
        ls -al
        ls ./release
    
    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: packs
        path: |
          ./release/*/*dmg # mac 安装包
          ./release/*/*exe # window 安装包
          ./release/*/*snap # linux 安装包