# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest] 

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install and Pack # 安装依赖并且进行构建
      run: |
        npm install
        npm run build

    - name: Echo pwd and ls
      run: |
        pwd
        ls -al
    - name: Echo release
      run: |
        ls ./release
    
    - name: Upload file
      with:
        name: uploads
        path: |
          curl --silent \
               --request POST \
               --url "$upload_url?name=$filename" \
               --header "authorization: Bearer $github_token" \
               --header "content-type: $content_type" \
               --data-binary @"$filepath"
